### ISSUE TITLE
how to insert array data into configuration file ?

### ISSUE THREAD

**Issue by restuwahyu13** [luraproject/lura#476] opened 2021-04-13 18:36 UTC
I have following this [tutorial](https://www.krakend.io/docs/configuration/flexible-config/) for setting configuration my krakend config, if I use the object, ok config is working, but if I use array config is not working, because headers_to_pass and backend is array not object, can you help me with this issue?

## krakend.json

```json
{
	"version": 2,
	"name": "Express API Gateway Production",
	"max_idle_connections": 200,
	"extra_config":{
		{{ include "krakend_cors.tpl" }},
		{{ include "krakend_gobreaker.tpl" }},
		{{ include "krakend_gologging.tpl" }},
		{{ include "krakend_proxy.tpl" }}
	},
	"endpoints": [
		{{ range .test.route_group }}
		{
			"endpoint": "{{ .endpoint }}",
			"method": "{{ .method }}",
			"concurrent_calls": "{{ .concurrent_calls }}",
			"headers_to_pass": {{ .headers_to_pass }},
			"output_encoding": "{{ .output_encoding }}",
			"cache_ttl": "{{ .cache_ttl }}",
			"timeout": "{{ .timeout }}",
                        "backend": "{{ .backend }}"
		}
		{{ end }}
	]
}
```
## test.json

```json
{
	"route_group": [
		{
			"@comment": "login authentication",
			"endpoint": "/login",
			"method": "POST",
			"concurrent_calls": 1,
			"headers_to_pass": ["Accept-Encoding", "Content-Type", "Content-Lenght", "Host", "Origin", "User-Agent"],
			"output_encoding": "no-op",
			"cache_ttl": "3600ms",
			"timeout": "7200ms",
			"backend": [
				{
					"host": ["http://book-service:3000"],
					"method": "POST",
					"url_pattern": "/api/v1/auth/login",
					"encoding": "no-op",
					"is_collection": false,
					"disable_host_sanitize": false,
					"timeout": "14400ms"
				}
			]
		},
		{
			"@comment": "register authentication",
			"endpoint": "/register",
			"method": "POST",
			"concurrent_calls": 1,
			"headers_to_pass": ["Accept-Encoding", "Content-Type", "Content-Lenght", "Host", "Origin", "User-Agent"],
			"output_encoding": "no-op",
			"cache_ttl": "3600ms",
			"timeout": "7200ms",
			"backend": [
				{
					"host": ["http://book-service:3000"],
					"method": "POST",
					"url_pattern": "/api/v1/auth/register",
					"encoding": "no-op",
					"is_collection": false,
					"disable_host_sanitize": false,
					"timeout": "14400ms",
				}
			]
		}
	]
}
```

**Comment by kpacha** [comment] 2021-04-13 18:41
did you try with `{{ marshal .headers_to_pass }}`? because you want the json representation of the value (in this case, an array)

**Comment by restuwahyu13** [comment] 2021-04-13 18:53
but if I use with one value is working and I use two value is not working, please check my code below sir

## Working With One Data

```sh
Sending build context to Docker daemon  31.74kB
Step 1/7 : FROM devopsfaith/krakend:latest
 ---> aa0afe25927f
Step 2/7 : USER ${USER}
 ---> Running in 9af12c5c54ea
Removing intermediate container 9af12c5c54ea
 ---> 6a62f9600827
Step 3/7 : WORKDIR /usr/src/krakend
 ---> Running in 3070774d4896
Removing intermediate container 3070774d4896
 ---> db1824c0ecda
Step 4/7 : COPY ./krakend.json   ./scripts/check.sh ./
 ---> 2013314b3d50
Step 5/7 : COPY . ./
 ---> 236b265044dc
Step 6/7 : RUN chmod 777 -R ./check.sh   && chmod a+x ./check.sh
 ---> Running in f4f2d583e046
Removing intermediate container f4f2d583e046
 ---> 994004ce03f3
Step 7/7 : ENTRYPOINT [ "./check.sh" ]
 ---> Running in 972ae9fd1da5
Removing intermediate container 972ae9fd1da5
 ---> 3a9be842b965
Successfully built 3a9be842b965
Successfully tagged krakend-check:latest
Parsing configuration file: /usr/src/krakend/krakend.json
Syntax OK!
[antimalware@antimalware-h81ms2pv krakend]$
```
## Not Working With Two Data

```sh
[antimalware@antimalware-h81ms2pv krakend]$ bash scripts/command.sh
Sending build context to Docker daemon  32.77kB
Step 1/7 : FROM devopsfaith/krakend:latest
 ---> aa0afe25927f
Step 2/7 : USER ${USER}
 ---> Running in 2b63085716fe
Removing intermediate container 2b63085716fe
 ---> 3818fdb7b394
Step 3/7 : WORKDIR /usr/src/krakend
 ---> Running in 71fae260198b
Removing intermediate container 71fae260198b
 ---> db13eee0481c
Step 4/7 : COPY ./krakend.json   ./scripts/check.sh ./
 ---> 9094b32f281a
Step 5/7 : COPY . ./
 ---> c7fde0985f9a
Step 6/7 : RUN chmod 777 -R ./check.sh   && chmod a+x ./check.sh
 ---> Running in 146b06744d9a
Removing intermediate container 146b06744d9a
 ---> 77e8da0f5fd5
Step 7/7 : ENTRYPOINT [ "./check.sh" ]
 ---> Running in 0233ac2d640f
Removing intermediate container 0233ac2d640f
 ---> 1d844a856e2f
Successfully built 1d844a856e2f
Successfully tagged krakend-check:latest
Parsing configuration file: /usr/src/krakend/krakend.json
ERROR parsing the configuration file.
 '/tmp/KrakenD_parsed_config_template_194499942.json': invalid character '{' after array element, offset: 1693, row: 56, col: 3
[antimalware@antimalware-h81ms2pv krakend]$ 
```

## After Using Marshal

```json
{
	"version": 2,
	"name": "Express API Gateway Production",
	"max_idle_connections": 200,
	"extra_config":{
		{{ include "krakend_cors.tpl" }},
		{{ include "krakend_gobreaker.tpl" }},
		{{ include "krakend_gologging.tpl" }},
		{{ include "krakend_proxy.tpl" }}
	},
	"endpoints": [
		{{ range .test.route_group }}
		{
			"endpoint": "{{ .endpoint }}",
			"method": "{{ .method }}",
			"concurrent_calls": "{{ .concurrent_calls }}",
			"headers_to_pass": {{ marshal .headers_to_pass }},
			"output_encoding": "{{ .output_encoding }}",
			"cache_ttl": "{{ .cache_ttl }}",
			"timeout": "{{ .timeout }}",
			"backend": {{ marshal .backend }}
		}
		{{ end }}
	]
}
```

## test.json

```json
{
	"route_group": [
		{
			"@comment": "login authentication",
			"endpoint": "/login",
			"method": "POST",
			"concurrent_calls": 1,
			"headers_to_pass": ["Accept-Encoding", "Content-Type", "Content-Lenght", "Host", "Origin", "User-Agent"],
			"output_encoding": "no-op",
			"cache_ttl": "3600ms",
			"timeout": "7200ms",
			"backend": [
				{
					"host": ["http://book-service:3000"],
					"method": "POST",
					"url_pattern": "/api/v1/auth/login",
					"encoding": "no-op",
					"is_collection": false,
					"disable_host_sanitize": false,
					"timeout": "14400ms",
					"extra_config": {
						"github.com/devopsfaith/krakend-jsonschema": {
							"type": "object",
							"properties": {
								"status": {
									"type": "string"
								},
								"code": {
									"type": "integer"
								},
								"method": {
									"type": "string"
								},
								"message": {
									"type": "string"
								},
								"accessToken": {
									"type": "string"
								}
							},
							"required": ["status", "code", "method", "message"]
						}
					}
				}
			]
		},
		{
			"@comment": "register authentication",
			"endpoint": "/register",
			"method": "POST",
			"concurrent_calls": 1,
			"headers_to_pass": ["Accept-Encoding", "Content-Type", "Content-Lenght", "Host", "Origin", "User-Agent"],
			"output_encoding": "no-op",
			"cache_ttl": "3600ms",
			"timeout": "7200ms",
			"backend": [
				{
					"host": ["http://book-service:3000"],
					"method": "POST",
					"url_pattern": "/api/v1/auth/register",
					"encoding": "no-op",
					"is_collection": false,
					"disable_host_sanitize": false,
					"timeout": "14400ms",
					"extra_config": {
						"github.com/devopsfaith/krakend-jsonschema": {
							"type": "object",
							"properties": {
								"status": {
									"type": "string"
								},
								"code": {
									"type": "integer"
								},
								"method": {
									"type": "string"
								},
								"message": {
									"type": "string"
								},
								"accessToken": {
									"type": "string"
								}
							},
							"required": ["status", "code", "method", "message"]
						}
					}
				}
			]
		}
	]
}

```

**Comment by alombarte** [comment] 2021-04-14 07:34
Hi @restuwahyu13 , the marshal is just fine. See that the linter of krakend is telling your where is the problem:
```
 '/tmp/KrakenD_parsed_config_template_194499942.json': invalid character '{' after array element, offset: 1693, row: 56, col: 3
```
If you inspect the output of the generated file (you can change it by setting the `FC_OUT` in the future) you'll see where the problem is. By looking at your example `test.json` I just saw that you have an extra comma at the end of the `backend` definition that you should remove:
```
{
			"@comment": "register authentication",
			"endpoint": "/register",
			"method": "POST",
			"concurrent_calls": 1,
			"headers_to_pass": ["Accept-Encoding", "Content-Type", "Content-Lenght", "Host", "Origin", "User-Agent"],
			"output_encoding": "no-op",
			"cache_ttl": "3600ms",
			"timeout": "7200ms",
			"backend": [
				{
					"host": ["http://book-service:3000"],
					"method": "POST",
					"url_pattern": "/api/v1/auth/register",
					"encoding": "no-op",
					"is_collection": false,
					"disable_host_sanitize": false,
					"timeout": "14400ms", <----------------------------------- PROBLEM
				}
			]
		}
```

**Comment by restuwahyu13** [comment] 2021-04-14 10:39
I removed the timeout, sir, as you said, but this error keeps coming back, what's wrong with my configuration?

## Krakend.json
```json
{
	"version": 2,
	"name": "Express API Gateway Production",
	"max_idle_connections": 200,
	"extra_config":{
		{{ include "krakend_cors.tpl" }},
		{{ include "krakend_gobreaker.tpl" }},
		{{ include "krakend_gologging.tpl" }},
		{{ include "krakend_proxy.tpl" }}
	},
	"endpoints": [
		{{ range .test.route }}
		{
			"@comment": "login authentication",
			"endpoint": "{{ .endpoint }}",
			"method": "{{ .method }}",
			"concurrent_calls": "{{ .concurrent_calls }}",
			"headers_to_pass": {{ marshal .headers_to_pass }},
			"output_encoding": "{{ .output_encoding }}",
			"cache_ttl": "{{ .cache_ttl }}",
			"timeout": "{{ .timeout }}",
			"backend": {{ marshal .backend }}
		}
		{{ end }}
	]
}
```

## testing.json after remove timeout

```json
{
	"route": [
		{
			"@comment": "login authentication",
			"endpoint": "/login",
			"method": "POST",
			"concurrent_calls": 1,
			"headers_to_pass": [
				"Accept-Encoding",
				"Accept-Language",
				"access-control-allow-origin",
				"Access-Control-Request-Headers",
				"Access-Control-Request-Method",
				"Authorization",
				"Cache-Control",
				"Connection",
				"Content-Type",
				"Host",
				"If-Modified-Since",
				"Keep-Alive",
				"Key",
				"Origin",
				"Pragma",
				"User-Agent",
				"X-Custom-Header"
			],
			"output_encoding": "no-op",
			"cache_ttl": "3600ms",
			"timeout": "7200ms",
			"backend": [
				{
					"host": ["http://book-service:3000"],
					"method": "POST",
					"url_pattern": "/api/v1/auth/login",
					"encoding": "no-op",
					"is_collection": false,
					"disable_host_sanitize": false
				}
			]
		},
		{
			"@comment": "register authentication",
			"endpoint": "/register",
			"method": "POST",
			"concurrent_calls": 1,
			"headers_to_pass": [
				"Accept-Encoding",
				"Accept-Language",
				"access-control-allow-origin",
				"Access-Control-Request-Headers",
				"Access-Control-Request-Method",
				"Authorization",
				"Cache-Control",
				"Connection",
				"Content-Type",
				"Host",
				"If-Modified-Since",
				"Keep-Alive",
				"Key",
				"Origin",
				"Pragma",
				"User-Agent",
				"X-Custom-Header"
			],
			"output_encoding": "no-op",
			"cache_ttl": "3600ms",
			"timeout": "7200ms",
			"backend": [
				{
					"host": ["http://book-service:3000"],
					"method": "POST",
					"url_pattern": "/api/v1/auth/register",
					"encoding": "no-op",
					"is_collection": false,
					"disable_host_sanitize": false
				}
			]
		}
	]
}
````
### My CLI
```sh
[antimalware@antimalware-h81ms2pv krakend]$ make check
Sending build context to Docker daemon  40.45kB
Step 1/7 : FROM devopsfaith/krakend:latest
 ---> aa0afe25927f
Step 2/7 : USER ${USER}
 ---> Running in 83f3fbda3db3
Removing intermediate container 83f3fbda3db3
 ---> 1ec17355fd07
Step 3/7 : WORKDIR /usr/src/krakend
 ---> Running in d5e54ebfd17e
Removing intermediate container d5e54ebfd17e
 ---> 671c47e95379
Step 4/7 : COPY ./krakend.json   ./scripts/check.sh ./
 ---> fb0849dbdfac
Step 5/7 : COPY . ./
 ---> 4454d72f8031
Step 6/7 : RUN chmod 777 -R ./check.sh   && chmod a+x ./check.sh
 ---> Running in 7f0ba0d5be1e
Removing intermediate container 7f0ba0d5be1e
 ---> ec67b4222795
Step 7/7 : ENTRYPOINT [ "./check.sh" ]
 ---> Running in 4746d49d1f25
Removing intermediate container 4746d49d1f25
 ---> b0e86082b30b
Successfully built b0e86082b30b
Successfully tagged krakend-check:latest
Parsing configuration file: /usr/src/krakend/krakend.json
ERROR parsing the configuration file.
 '/tmp/KrakenD_parsed_config_template_287852247.json': invalid character '{' after array element, offset: 1811, row: 64, col: 3
make: *** [Makefile:12: check] Error 1
[antimalware@antimalware-h81ms2pv krakend]$ 
```

**Comment by alombarte** [comment] 2023-06-22 08:01
Hi @restuwahyu13,

Can we close this issue?

**Closed** 2023-06-22 08:07 UTC
Labels: question
